### ISSUE TITLE
Add a README with information on building documentation

### ISSUE THREAD

**Issue by DCRichards** [slamdata/slamdata-docs#10]
Those interested in previewing future version of the documentation (eg. for the upcoming 3.0 release)  could do so more easily with some instructions on building. This should include prerequisite, build instructions and a short explanation on tooling/libraries used for those unfamiliar.

**Comment by damonLL** [comment]
Given the changes in store for future versions of SlamData, I am creating a document that explains how to edit the SlamData documentation, not necessarily on how to build it (just yet). I'll create another task for that.

**Comment by damonLL** [comment]
Created new README.md via PR #22
